CREATE TABLE FUNCIONARIO(
ID_FUNCIONARIO INTEGER,
NOME VARCHAR(200),
FUNCAO VARCHAR(50),
EMAIL VARCHAR(200));
ALTER TABLE FUNCIONARIO ADD ID_LOTACAO INTEGER;
ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_LOTACAO FOREIGN KEY (ID_LOTACAO) REFERENCES LOTACAO(ID_LOTACAO);

CREATE TABLE LOTACAO(
ID_LOTACAO INTEGER,
DESCRICAO VARCHAR(200));
ALTER TABLE LOTACAO ADD ID_COZINHA INTEGER;
ALTER TABLE LOTACAO ADD CONSTRAINT PK_LOTACAO PRIMARY KEY (ID_LOTACAO);
ALTER TABLE LOTACAO ADD CONSTRAINT FK_COZINHA FOREIGN KEY (ID_COZINHA) REFERENCES COZINHA(ID_COZINHA);

CREATE TABLE COZINHA(
ID_COZINHA INTEGER);
ALTER TABLE COZINHA ADD CONSTRAINT PK_COZINHA PRIMARY KEY (ID_COZINHA);

COMMIT;